@echo off
setlocal enabledelayedexpansion

set "SCRIPT_DIR=%~dp0"
if "!SCRIPT_DIR:~-1!"=="\" set "SCRIPT_DIR=!SCRIPT_DIR:~0,-1!"

rem Primary: use .drift.env (generated by drift eject, drift compile, or driftw self-heal)
if exist "!SCRIPT_DIR!\.drift.env" (
    for /f "usebackq eol=# tokens=1,* delims==" %%a in ("!SCRIPT_DIR!\.drift.env") do (
        if "%%a"=="DRIFT_BIN" set "DRIFT_BIN=%%~b"
        if "%%a"=="GO_BIN" set "GO_BIN=%%~b"
    )
    if exist "!DRIFT_BIN!" (
        if defined GO_BIN for %%G in ("!GO_BIN!") do set "PATH=%%~dpG;!PATH!"
        "!DRIFT_BIN!" %*
        exit /b !errorlevel!
    )
)

rem Add Go binary paths for discovery
if defined GOBIN if exist "%GOBIN%" set "PATH=%GOBIN%;!PATH!"
if defined GOPATH if exist "%GOPATH%\bin" set "PATH=%GOPATH%\bin;!PATH!"
if exist "%USERPROFILE%\go\bin" set "PATH=%USERPROFILE%\go\bin;!PATH!"

rem Resolve drift and go from PATH
set "DRIFT_BIN="
set "GO_BIN="
for %%i in (drift.exe) do set "DRIFT_BIN=%%~$PATH:i"
for %%i in (go.exe) do set "GO_BIN=%%~$PATH:i"

if not defined DRIFT_BIN goto :notfound
if not exist "!DRIFT_BIN!" goto :notfound

rem Self-heal: write .drift.env so future builds skip PATH augmentation
(
    echo # Auto-generated by driftw. Do not commit.
    echo DRIFT_BIN="!DRIFT_BIN!"
    if defined GO_BIN echo GO_BIN="!GO_BIN!"
) > "!SCRIPT_DIR!\.drift.env" 2>nul

"!DRIFT_BIN!" %*
exit /b !errorlevel!

:notfound
echo Error: drift not found. >&2
for %%P in ("!SCRIPT_DIR!\..") do set "PLATFORM=%%~nP"
echo Install drift and run 'drift compile !PLATFORM!' from your terminal, >&2
echo or install with: go install github.com/go-drift/drift/cmd/drift@latest >&2
exit /b 1
