import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        description: 'Learn how to build apps with Drift.',
      },
      items: [
        'guides/getting-started',
        'guides/widgets',
        'guides/lists',
        'guides/layout',
        'guides/theming',
        'guides/state-management',
        'guides/forms',
        'guides/gestures',
        'guides/navigation',
        'guides/overlay',
        'guides/animation',
        'guides/platform',
        'guides/media-player',
        'guides/accessibility',
        'guides/error-handling',
        'guides/debugging',
        'guides/testing',
        'guides/skia',
        'guides/xtool-setup',
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        description: 'API documentation generated from Go source code.',
      },
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
  ],
};

export default sidebars;
