import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        description: 'Learn how to build apps with Drift.',
      },
      items: [
        'guides/getting-started',
        'guides/widgets',
        'guides/layout',
        'guides/state-management',
        'guides/theming',
        'guides/forms',
        'guides/animation',
        'guides/navigation',
        'guides/overlay',
        'guides/gestures',
        'guides/platform',
        'guides/media-player',
        'guides/accessibility',
        'guides/error-handling',
        'guides/debugging',
        'guides/testing',
        'guides/skia',
        'guides/xtool-setup',
      ],
    },
    {
      type: 'category',
      label: 'Widget Catalog',
      link: {
        type: 'generated-index',
        description: 'Find detailed usage for every Drift widget.',
      },
      items: [
        {
          type: 'category',
          label: 'Layout',
          items: [
            'catalog/layout/column-row',
            'catalog/layout/stack-positioned',
            'catalog/layout/wrap',
            'catalog/layout/container-decoratedbox',
            'catalog/layout/sizedbox',
            'catalog/layout/padding',
            'catalog/layout/expanded-flexible',
            'catalog/layout/center-align',
            'catalog/layout/safearea',
            'catalog/layout/layout-builder',
          ],
        },
        {
          type: 'category',
          label: 'Display',
          items: [
            'catalog/display/text',
            'catalog/display/icon',
            'catalog/display/image-svg',
          ],
        },
        {
          type: 'category',
          label: 'Input',
          items: [
            'catalog/input/button',
            'catalog/input/textfield',
            'catalog/input/checkbox-radio',
            'catalog/input/switch-toggle',
            'catalog/input/dropdown',
            'catalog/input/datepicker-timepicker',
          ],
        },
        {
          type: 'category',
          label: 'Lists & Scrolling',
          items: [
            'catalog/scrolling/listview',
            'catalog/scrolling/scrollview',
          ],
        },
        {
          type: 'category',
          label: 'Feedback',
          items: [
            'catalog/feedback/progress-indicators',
            'catalog/feedback/error-boundary',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        description: 'API documentation generated from Go source code.',
      },
      items: [
        {type: 'autogenerated', dirName: 'api'},
      ],
    },
  ],
};

export default sidebars;
